### ISSUE TITLE
Huge Performance issue of PUT

### ISSUE THREAD

**Issue by AvnerCohen** [typhoeus/ethon#115]
Hi, I imagine this is an ethon issue and not tyephous, but I'm totally unsure.

I've defined a simple api end point with both POST and PUT.

Than benchmarked, result are quite crazy:

``` sh
                     user     system      total        real
put_with_data    0.010000   0.000000   0.010000 ( 11.060901)
put_with_nil     0.010000   0.000000   0.010000 ( 11.054922)
post_with_data   0.000000   0.000000   0.000000 (  0.011259)
post_with_nil    0.010000   0.000000   0.010000 (  0.012506)
```

Note the slowness in case of PUT (vs POST), regardless of any payload.

Here is the full benchmarking code:

``` ruby
require 'benchmark'
require 'json'

require 'bundler'
Bundler.require

def run_one_request(payload, method )
  headers = {}
  if payload.respond_to?(:to_json)
    payload = payload.to_json
  end  
  request = Typhoeus::Request.new('http://127.0.0.1:9292/ping', { headers: headers, method: method, body: payload })
  request.run
end

COUNTER = 10
Benchmark.bmbm do |repo|
  repo.report("put_with_data") do
    0.upto(COUNTER) { run_one_request({}, 'PUT') }
  end
  repo.report("put_with_nil")  do
    0.upto(COUNTER) { run_one_request(nil, 'PUT') }
  end
  repo.report("post_with_data")  do
    0.upto(COUNTER) { run_one_request({}, 'POST') }
  end
  repo.report("post_with_nil")  do
    0.upto(COUNTER) { run_one_request(nil, 'POST') }
  end


end
```

Issue #3 made me think that maybe something was missed out.

I also noticed that postable.rb and putable.rb are very different, where I imagined they should be very similar, but I might be wrong.

Any suggestions other than totally avoiding PUT requests ?

**Comment by AvnerCohen** [comment]
Stackprof results for the case of POST:

````sh
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
         6  (60.0%)           6  (60.0%)     FFI::Pointer#read_string
         9  (90.0%)           2  (20.0%)     block (2 levels) in <main>
         7  (70.0%)           1  (10.0%)     Ethon::Easy::Operations#perform
         7  (70.0%)           0   (0.0%)     Typhoeus::Request::Cacheable#run
         9  (90.0%)           0   (0.0%)     <main>
         7  (70.0%)           0   (0.0%)     Typhoeus::Request::Operations#run
         9  (90.0%)           0   (0.0%)     <main>
         7  (70.0%)           0   (0.0%)     Typhoeus::Request::BlockConnection#run
         7  (70.0%)           0   (0.0%)     Typhoeus::Request::Stubbable#run
         7  (70.0%)           0   (0.0%)     Typhoeus::Request::Before#run
         9  (90.0%)           0   (0.0%)     block in <main>
         6  (60.0%)           0   (0.0%)     block in Ethon::Easy::Callbacks#header_write_callback
````

Vs that of PUT:
````
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
         5  (38.5%)           4  (30.8%)     block in Ethon::Easy::Callbacks#set_read_callback
        13 (100.0%)           2  (15.4%)     block (2 levels) in <main>
         7  (53.8%)           2  (15.4%)     Ethon::Easy::Operations#perform
         1   (7.7%)           1   (7.7%)     Typhoeus::EasyFactory#easy
         2  (15.4%)           1   (7.7%)     Ethon::Curls::Options#set_option
         1   (7.7%)           1   (7.7%)     FFI::Enum#to_native
         1   (7.7%)           1   (7.7%)     FFI::Pointer#write_string
         1   (7.7%)           1   (7.7%)     Typhoeus::Request#initialize
        10  (76.9%)           0   (0.0%)     Typhoeus::Request::Before#run
        13 (100.0%)           0   (0.0%)     block in <main>
        10  (76.9%)           0   (0.0%)     Typhoeus::Request::Stubbable#run
        13 (100.0%)           0   (0.0%)     <main>
        10  (76.9%)           0   (0.0%)     Typhoeus::Request::BlockConnection#run
        10  (76.9%)           0   (0.0%)     Typhoeus::Request::Cacheable#run
         2  (15.4%)           0   (0.0%)     Ethon::Easy::Options#url=
         2  (15.4%)           0   (0.0%)     Ethon::Easy::Http::Actionable#setup
         2  (15.4%)           0   (0.0%)     Ethon::Easy::Http::Put#setup
         2  (15.4%)           0   (0.0%)     Ethon::Easy::Http#http_request
         3  (23.1%)           0   (0.0%)     Typhoeus::EasyFactory#get
        10  (76.9%)           0   (0.0%)     Typhoeus::Request::Operations#run
        13 (100.0%)           0   (0.0%)     <main>
````

**Comment by AvnerCohen** [comment]
Last input I see on this. commenting out the "upload = true" line in putable:
https://github.com/typhoeus/ethon/blob/master/lib/ethon/easy/http/putable.rb#L15

Solves the issue, but I guess it breaks something else I'm not aware about... :)

**Comment by i0rek** [comment]
@AvnerCohen thanks for your investigation! Thats very interesting. In libcurl there is often more than one way to do a `METHOD` call. With `PUT` using `upload` is the recommended way: http://curl.haxx.se/libcurl/c/CURLOPT_PUT.html and http://curl.haxx.se/libcurl/c/CURLOPT_UPLOAD.html. That a blog post post touching this subject es well: http://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/.
I wonder though if there is a better way to `PUT`.

**Comment by linrock** [comment]
This performance problem with `PUT` happens when libcurl sends the `Expect: 100-Continue` header to servers that don't reply with status code `100` status right away. In those situations, libcurl waits for an extra 1s per request before actually sending the request body.

More info about this:
http://stackoverflow.com/questions/17383089/libcurl-delays-for-1-second-before-uploading-data-command-line-curl-does-not
https://support.urbanairship.com/entries/59909909--Expect-100-Continue-Issues-and-Risks

--

@AvnerCohen according to https://curl.haxx.se/libcurl/c/CURLOPT_UPLOAD.html using `upload = true` automatically implies use of `Expect: 100-Continue`, which is why removing that line solves the issue.

If the `Expect: 100-Continue` header is disabled for `PUT` requests in ethon, the performance problem goes away.

For example, in the above benchmarking code, this will fix the slowness:

```ruby
headers = { 'Expect' => ''}
```

**Comment by AvnerCohen** [comment]
Thanks @linrock this is really useful !

@i0rek this is some great info, I can see why we one would want the more "raw" behavior in ethon, how about meging `headers = { 'Expect' => ''}` as a default value to PUT calls in:
https://github.com/typhoeus/typhoeus/blob/d9e6dce92a04754a2276c94393dad0f3a5c06bdd/lib/typhoeus/request/actions.rb#L57
?

@linrock what do you think? would that be a better default behavior,  or there a risk in that?

**Comment by i0rek** [comment]
damn, I forgot about the `Expect` header! Ethon uses it itself in the tests for every `PUT` call eg: https://github.com/typhoeus/ethon/blob/7269d06ddc5ad60a0048fb76ba12511126a55dac/spec/ethon/easy/http/put_spec.rb#L131. I think I would be up for disabling the expect header sending like @AvnerCohen  suggested.

**Comment by AvnerCohen** [comment]
Thanks @i0rek just to be 100% sure, you'd rather have the PR and code change in Eython or typhoeus ?

**Comment by i0rek** [comment]
if you find a good place in typhoeus, lets put it in there.

**Comment by linrock** [comment]
Sounds good, I agree it's a better default behavior to remove the `Expect` header, either in ethon or typhoeus.

@AvnerCohen I don't think there's a risk in removing the header, and it'd definitely speed up requests in situations where servers don't handle it correctly

**Comment by Kjarrigan** [comment]
The change was made and merged into typhoeus as suggested. So closing.
