### ISSUE TITLE
Add support for curl PIPEWAIT option

### ISSUE THREAD

**Issue by drpump** [typhoeus/ethon#148]
Multiplexing over HTTP2 is unreliable unless the (relatively new) PIPEWAIT option is used. See the **Multiplexing** section of https://curl.haxx.se/docs/http2.html. 

Can we add support for the PIPEWAIT option in multi?

**Comment by i0rek** [comment]
> Can we add support for the PIPEWAIT option in multi?

of course, if you send a PR I would happily merge!

**Comment by drpump** [comment]
Thanks. Will do.
