### ISSUE TITLE
Deprecate error code 51

### ISSUE THREAD

**Issue by Medvezo** [typhoeus/ethon#157]
`CURLE_PEER_FAILED_VERIFICATION` was merged with `CURLE_SSL_CACERT` in 7.62: https://github.com/curl/curl/pull/2901

Error code 51 was obsoleted: https://github.com/curl/curl/blob/ae99b4de1c443ae9892b1c0fc2b39e3afe73c4bc/include/curl/curl.h

However, typhoeus still returns `ssl_cacert` code: https://github.com/typhoeus/ethon/blob/de60a72552a1ae392705617a45477d93f0f51293/lib/ethon/curls/codes.rb#L72

**Comment by PericlesTheo** [comment]
Thanks for the heads up. I will mark it as good first issue and pass it on to someone
