### ISSUE TITLE
Gem fails to initialize when mounted in a read-only filesystem

### ISSUE THREAD

**Issue by ben** [typhoeus/ethon#189]
I'm running a Rails app in Kubernetes, and the root filesystem is mounted as read-only. On startup using 0.13.0, I get an exception with this as the first few lines of the stacktrace:

```
Read-only file system @ rb_sysopen - /app/.const_generator20210415-16-174j4gr
/usr/lib/ruby/2.7.0/tempfile.rb:129:in `initialize'
/usr/lib/ruby/2.7.0/tempfile.rb:129:in `open'
/usr/lib/ruby/2.7.0/tempfile.rb:129:in `block in initialize'
/usr/lib/ruby/2.7.0/tmpdir.rb:129:in `create'
/usr/lib/ruby/2.7.0/tempfile.rb:127:in `initialize'
/usr/lib/ruby/2.7.0/tempfile.rb:287:in `new'
/usr/lib/ruby/2.7.0/tempfile.rb:287:in `open'
/usr/bundle/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:110:in `calculate'
/usr/bundle/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:49:in `initialize'
/usr/bundle/ruby/2.7.0/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `new'
/usr/bundle/ruby/2.7.0/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `<module:Libc>'
/usr/bundle/ruby/2.7.0/gems/ethon-0.13.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
/usr/bundle/ruby/2.7.0/gems/ethon-0.13.0/lib/ethon/libc.rb:2:in `<top (required)>'
```

Looks like between 0.12.0 and 0.13.0 there was [a change](https://github.com/typhoeus/ethon/compare/v0.12.0...v0.13.0#diff-370272df6fcde26ffc392d575d0643f1564781713d56c54485479edde428d6cbL16-R31) that introduced the use of `FFI::ConstGenerator`, whose [default initializer](https://github.com/ffi/ffi/blob/4430b6d5fe720f9cb84a845a0bee9abf23e22cea/lib/ffi/tools/const_generator.rb#L39) sets it up to write to the current directory.

Could ethon initialize the ConstGenerator to use `ENV['TMPDIR'] || '/tmp'` instead of the default?

**Comment by Kjarrigan** [comment]
Hm. Not sure if this is possible. Because the line that crashed is https://github.com/ffi/ffi/blob/master/lib/ffi/tools/const_generator.rb#L110 and `Tempfile.open`s second param (which is not set in FFI) is used to change the [temp_dir](https://ruby-doc.org/stdlib-2.7.3/libdoc/tempfile/rdoc/Tempfile.html#method-c-open)

But in https://github.com/ffi/ffi/blob/master/lib/ffi/tools/const_generator.rb#L108 they already use Dir.tmpdir for the _binary_ so I think you could open a FFI-Pullrequest to use it for Tempfile.open too

**Comment by ben** [comment]
The [line that opens the file](https://github.com/ffi/ffi/blob/4430b6d5fe720f9cb84a845a0bee9abf23e22cea/lib/ffi/tools/const_generator.rb#L110) uses `"#{@prefix}.const_generator"` as the filename. `@prefix` is set [in the initializer](https://github.com/ffi/ffi/blob/4430b6d5fe720f9cb84a845a0bee9abf23e22cea/lib/ffi/tools/const_generator.rb#L42). So if ethon were to do this at [the callsite](https://github.com/typhoeus/ethon/blob/b3d93050dbb2329b3d21d7a20e0d1af6f7d4abed/lib/ethon/libc.rb#L17):

```rb
fcg = FFI::ConstGenerator.new(ENV['TMPDIR'] || '/tmp') do |gen|
```

…I believe that would solve this issue.

**Comment by tagliala** [comment]
Hi, I had a similar issue because FFI was attempting to execute a file in the tmp `dir`

Any chance to TL;DR what that binary does?

**Comment by Kjarrigan** [comment]
@ben I don't think so¹ but feel free to try it out. After all this is Ruby and you can change all the code you want. 

¹The prefix of a tempfile only influences the filename as you can see in the docs I linked.

**Comment by Kjarrigan** [comment]
Should be solved in the next version. See #185
