### ISSUE TITLE
0.16.0 changelog

### ISSUE THREAD

**Issue by tagliala** [typhoeus/ethon#222]
Hi, is it possible to have a changelog of the latest release so I can consider the upgrade?

For the moment I'm comparing tags: https://github.com/typhoeus/ethon/compare/v0.15.0...v0.16.0

**Comment by Kjarrigan** [comment]
Hi, comparing the  tags is the way to go at the moment. If you look at the CHANGELOG.md that's basically how this has been since the very beginning. I'll add the link there soon-ish but there won't be a written version I fear, unless you're willing to write one, which I would be happy to merge.
