### ISSUE TITLE
Support HTTP PURGE verb (and maybe other custom ones)

### ISSUE THREAD

**Issue by corasaurus-hex** [typhoeus/ethon#35]
I'm not sure if this belongs in Typhoeus or Ethon, but Typhoeus used to support HTTP PURGE which is used by HTTP caches like Varnish to signal that entries should be removed.

The error I get now is: `uninitialized constant Ethon::Easy::Http::Purge`.

If I add this, the request works (it just copies Ethon::Easy::Http::Get):

``` ruby
module Ethon
  class Easy
    module Http

      # This class knows everything about making GET requests.
      class Purge
        include Ethon::Easy::Http::Actionable
        include Ethon::Easy::Http::Postable

        # Setup easy to make a GET request.
        #
        # @example Setup.
        #   get.set_params(easy)
        #
        # @param [ Easy ] easy The easy to setup.
        def setup(easy)
          super
          easy.customrequest = "GET" unless form.empty?
        end
      end
    end
  end
end
```

But maybe there's a way to allow for custom HTTP verbs?

**Comment by GabrSaac** [comment]
Hi, any help on this? :) http://stackoverflow.com/questions/35632607/is-the-http-verb-purge-idempotent
Thanks
