### ISSUE TITLE
Frozen after "ETHON: Libcurl initialized" from Typheous

### ISSUE THREAD

**Issue by hrdwdmrbl** [typhoeus/ethon#70]
My server freezes right after that line is output. I'm doing a simple request of the form

```
Typhoeus.get(request_url,
    headers: headers.merge({'Content-Type' => 'application/json'})
  )
```

This happens every time. I'm using Ethon 0.5.3 and curl "7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5".

Commenting out those lines solves my freezing issue. I even tried putting a timeout around those lines of code, but that did nothing to help.

Any help would be greatly appreciated. I know that 7.31 is out now, so I'm going to try updating to that.

**Comment by itssasanka** [comment]
@hrdwdmrbl  That was exactly what was happening in my case as well. All that freeze was just because it was waiting to connect to an external service and it waited out until the thing finally timed out.
