### ISSUE TITLE
All version of Ruby core dump in ethon running wpstools (wpscan)

### ISSUE THREAD

**Issue by davidfavor** [typhoeus/ethon#91]
https://bugs.ruby-lang.org/issues/10301 - Ruby bug ticket, where they referred the bug to ethon.

https://github.com/wpscanteam/wpscan/issues/699 - Original wpscan bug.

**Comment by blysik** [comment]
Note this same exact segfault exists when I use the curb gem.

The interesting bit is that if I just execute commands in irb, it's fine.

If I run the same code in the rails console, I get the segfault.

**Comment by blysik** [comment]
So... this is odd.  If I comment this line from my Gemfile, I don't get the segfault:
 gem 'spring-commands-rspec'

**Comment by jemc** [comment]
> So... this is odd. If I comment this line from my Gemfile, I don't get the segfault:
gem 'spring-commands-rspec'

That probably means this issue has something to do with forking.

**Comment by i0rek** [comment]
libcurl is threadsafe, but one must be careful. A hydra for example cannot be used across threads. maybe the gem forks, but does that accidentially.

**Comment by niko-pax-uofa** [comment]
This appears to be the same issue as https://github.com/typhoeus/typhoeus/issues/452

**Comment by Kjarrigan** [comment]
Closing this as there has been no update for some years now. If you still encounter this issue I'll reopen. Might have been fixed by #136 so if you have the issue please try the master-version.
