### ISSUE TITLE
Libcurl 7.19 vs Libcurl >7.30 escaping URL params

### ISSUE THREAD

**Issue by codecoded** [typhoeus/ethon#93]
Hi

I've recently decided to use the Typhoeus::Hydra gem to run parallel requests with a custom on_complete callback to process 3rd party API responses ASAP.

It works a charm in development, and I thought for a while on Heroku instance too. However, looking at the logs, it seems one of the 3rd party requests fails as the URL parameters are being escaped and I've located it down to the Ethon::Curl utility

The working example is on my Mac (OSX 10.9.5):
Ethon::Curl.version =>  "libcurl/7.30.0 SecureTransport zlib/1.2.5"

http://example.com?sdate=2014-10-27&hids=91847%2C245280%2C40245

hids is an int array [91847, 245280, 40245] which is meant to be escaped but running on Heroku which the Cedar stack uses Ubuntu 10.04 LTS:
Ethon::Curl.version => "libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15"

the url is
http://example.com?sdate=2014%2D10%2D27&hids=91847%2C245280%2C40245

Note, the sdate param is escaped from 2014-10-27 to 2014%2D10%2D27

Heroku have recently added a Cedar-14 stack which I'm testing my staging with and after upgrade I am seeing:
Ethon::Curl.version => "libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3"

And yes, the sdate is no longer escaped and the request works

Is there any settings in Ethon to help alleviate this issue without having to either handcraft a non-escaped query string or upgrade the production Heroku stack (which is a beta feature)

Many thanks
Sky

**Comment by luccasmaso** [comment]
Hi guys, I'm dealing with the same problem here! @Soultripper, what do you mean by appending the query string? Thanks!

**Comment by i0rek** [comment]
He included it into the url instead of providing the `param` option. That way it did not go through the escaping.
