### ISSUE TITLE
Ethon::Curls.easy_perform returning :couldnt_connect unexpectedly

### ISSUE THREAD

**Issue by jgandt** [typhoeus/ethon#94]
I'm using ethon through Typhoeus via Faraday for the elasticsearch gem.

The Ethon::Easy::Operations#perform method the call to Ethon::Curl.easy_perform unexpectedly returns `:couldnt_connect`.

I'm calling to localhost:9200. A browser request, manual wget, and `open('http://localhost:9200/')` returns the expected result. But somehow Ethon is unable to connect.

My Gemfile and .lock are in this [gist](https://gist.github.com/jgandt/4bd4439100a8a35588af).

I'm unsure as to how to continue debugging. Things dive into ffi, where things get scary for me. Please let me know what else I can provide so that I can improve this issue.

**Comment by jlowhy** [comment]
I encountered a similar problem. What I did was to change "localhost" into "127.0.0.1" and then the connection worked fine.
